insert into public.medications (medication_code, name, manufacturer, dosage_form, status, is_active)
values
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Acitrom 2mg Tab', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Acitrom 3mg Tab', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'AB-flo 100 mg Tab', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Aldactone 25mg Tab', 'Laborate', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Allercet pedtabs 5mg', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Amlong 10mg', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Amlokind 5mg Tab', 'Mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Amlokind 10mg Tab', 'Mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Anxit 0.25mg Tab', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Anxit 0.5mg Tab', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zyloric 100mg Tab', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Avil 25mg Tab', 'Sanofi', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Avil 50mg Tab', 'Sanofi', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Azoran 50mg Tab', 'Laborate', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Azithral 250mg', 'Alembic', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Azithral 500mg', 'Alembic', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Augmentin 375mg Tab', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Augmentin 625mg Tab', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Bandy plus', 'Mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Bacfon-10', 'icon', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'B-Long', 'Torcent pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Bilasure M', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Brufen 400mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Banocide Forte', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Candid v6', 'Glenmark', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cardigrel AS 75', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cardirose cold 10', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cardirose cold 20', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Capivit-forte', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Capi-Q forte', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Centrum', 'fssai', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Clicin 150', 'Indi pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Lumia 60K', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Carvidon-OD', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Carvil 3.125', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Carloc 6.25', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cerom-250', 'Ciplal', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cerom-500', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Cetcip 10mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Limcel', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Ciplox', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Concor-cor 2.5', 'Merck', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Chymoral forte', 'Torrent pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Daflon 500mg', 'Servier', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dapagold V5', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Deriphyllin', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'D3 must 2k', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dolonex  DT', 'Pfizer', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dox7-SL', 'Dr.Redyy''s', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Doxebet JR', 'BSV', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Digene', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dizzivert 16mg', 'Herodix', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Digoxino 25mg', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Drotikind-M', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dupbaston 10mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dulcoflex 5mg', 'Sanofi', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dytor 5mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Dytor 10mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Ecosprin-75', 'USV private limited', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Envas', 'Cardila', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Eptus-25', 'Glenmark', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Essentiale-L1g', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Etova-400', 'Ipca Laboratories', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Evion-200mg', 'procter&Gamble Health', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Embeta XR-25', 'INTAS', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Febustat 20mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Febustat 40mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Fericap-XT', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Flave Don', 'Servier', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Frisium 10mg', 'Sanofi', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Farobact 200', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Forecox', 'Macleods pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Freshlac', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Fertisure M', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Genvol', 'Candia pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Gramogyl', 'Ranbaxy', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'High caro', 'Sangrose', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Hical-M', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Head set', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Hairry Shine', 'Capital pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Isordil-5mg', 'Ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Isordil-10mg', 'Ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Ivepred 16', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Junior Lanzol15mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Ketoflam-P', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Kimet XL 25mg', 'Zuventus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Kimet XL 50MG', NULL, NULL, 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Librium 10mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Losakind 25mg', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Losakind 50mg', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Loparet 2mg', 'Retort Laboratories', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Agricare Plus Sachet', 'mmc', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Librax 5mg+2.5mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Levoflox 500mg', 'cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Lefno 10mg', 'ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Lupin''s Lupivon 20mg', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Medineuron', 'mmc pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'metrogyl', 'J.B.chemicals& Pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Proloment XL 25', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Metolar-50mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Prolomet XL 12.5mg', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Meprate', 'Maneesh pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Medineuron BT plus', NULL, 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Mexate 7.5mg', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Miso-Kare', 'DKT', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Mirago 25mg', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Mymi forte', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Myospaz forte', 'win-medicine', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Mymi max', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Montek', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Meftal', 'Blue cross', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Novamox-250mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Sachet Novefos', 'SRS', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Nofrosave', 'Fourrts', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Nodosis', 'Steadfast', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Norlut-N', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Nicardia retard 20mg', 'J.B chemicals', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Nuforce-150mg', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Nucoxia', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Tab.Nikoran-5', 'Torrent pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Olcure 20mg', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Olcure H20', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Olcure Trio20', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Olcure AM20', NULL, NULL, 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Omez-D+', 'Dr.Reddy''s', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Pan 40', 'Alkam', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Pan 20', 'Alkam', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'P.500', 'apex', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'P.650', 'micro labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'practin 4mg', 'Dr.Reddy''s', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Prothiaden 25', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Prednisolane 5mg', 'Vikram labs', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'wysolane 10mg', 'Pfizer', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Pulmoclear', 'Fourrts', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Qsita DM 500mg', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Rantac 150mg', 'J.B chemicals', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Rantac 300mg', 'J.B chemicals', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Rosuvas EZ 10mg', 'Emcure', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Rozavel 40mg', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Resodim 15mg', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Roseday-CV 20mg', 'USV', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Salazar', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Senasof', 'wanbury', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Stiloz-50', 'Integrace', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Silofast 8mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Syndopa 110', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Solvin cold', 'Ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Sporlac', 'J.B chemicals & pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Starpress XL (25)', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Stugeron forte', 'Jassen', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Susten 200mg', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Sysfol', 'ontop pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Sompraz D40', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Starizo 200mg', 'Sun pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Telma 40mg', 'Glenmark', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Telista-AM', 'Lupin', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Trapic 500mg', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Thiamin', 'Ordain healthcare', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Torget', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Trihexy', 'East west pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Udiliv 150mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Udiliv 300mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Urimax', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Veltam-F', 'Intas pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Vomikind-MD4', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Strip vomikind-fast', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Vertin 16mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Vertin 8mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Vasograin', 'Cadlla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Volicure Trio 1./0.3', 'HBC', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Vibacat', 'USV', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Warf-5mg', 'Cipla', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Xygrel 90mg', 'IntasPharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zerodol-SP', 'Ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zerodol-P', 'Ipca', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zenflox 200mg', 'mankind', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zedott', 'Torrent pharma', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zolfresh 5mg', 'Abbott', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zovirax', 'GSK', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zincovit.CD', 'Apex', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zyramod25mg', 'Zydus', 'Tablet', 'active', true),
( 'MED-' || replace(gen_random_uuid()::text,'-',''), 'Zincovit W', 'Apex', 'Tablet', 'active', true);
