-- Create table for uploaded patient bills (Supabase/PostgreSQL)
CREATE TABLE IF NOT EXISTS uploaded_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id VARCHAR(255) NOT NULL,
  patient_name VARCHAR(255) DEFAULT NULL,
  bill_date DATE DEFAULT NULL,
  total_amount DECIMAL(10,2) DEFAULT 0.00,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_data TEXT NOT NULL, -- Base64 encoded file data
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_allocation_id ON uploaded_bills(allocation_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_upload_date ON uploaded_bills(upload_date);

-- Add RLS (Row Level Security) for Supabase
ALTER TABLE uploaded_bills ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to read their own bills
CREATE POLICY "Users can view uploaded bills" ON uploaded_bills
  FOR SELECT USING (auth.role() = 'authenticated');

-- Create policy for authenticated users to insert bills
CREATE POLICY "Users can upload bills" ON uploaded_bills
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy for authenticated users to update their own bills
CREATE POLICY "Users can update uploaded bills" ON uploaded_bills
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policy for authenticated users to delete their own bills
CREATE POLICY "Users can delete uploaded bills" ON uploaded_bills
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_uploaded_bills_updated_at 
  BEFORE UPDATE ON uploaded_bills 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
