-- Create table for uploaded patient bills
CREATE TABLE IF NOT EXISTS uploaded_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id VARCHAR(255) NOT NULL,
  patient_name VARCHAR(255) DEFAULT NULL,
  bill_date DATE DEFAULT NULL,
  total_amount DECIMAL(10,2) DEFAULT 0.00,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_data TEXT NOT NULL,
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create performance indexes
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_allocation_id ON uploaded_bills(allocation_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_upload_date ON uploaded_bills(upload_date);

-- Enable Security
ALTER TABLE uploaded_bills ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to manage bills
CREATE POLICY "Users can manage bills" ON uploaded_bills FOR ALL USING (auth.role() = 'authenticated');
