
require('dotenv').config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

async function trySqlEndpoints() {
  const sql = `
CREATE TABLE IF NOT EXISTS uploaded_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id VARCHAR(255) NOT NULL,
  patient_name VARCHAR(255) DEFAULT NULL,
  bill_date DATE DEFAULT NULL,
  total_amount DECIMAL(10,2) DEFAULT 0.00,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_data TEXT NOT NULL,
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_allocation_id ON uploaded_bills(allocation_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_upload_date ON uploaded_bills(upload_date);
  `;

  const endpoints = [
    { url: `${supabaseUrl}/pg/query`, body: { query: sql } },
    { url: `${supabaseUrl}/rest/v1/rpc/exec_sql`, body: { sql: sql } },
    { url: `${supabaseUrl}/rest/v1/rpc/run_sql`, body: { sql: sql } },
  ];

  for (const endpoint of endpoints) {
    console.log(`Trying endpoint: ${endpoint.url}`);
    try {
      const response = await fetch(endpoint.url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': serviceKey,
          'Authorization': `Bearer ${serviceKey}`,
        },
        body: JSON.stringify(endpoint.body),
      });

      const text = await response.text();
      console.log(`Status: ${response.status}`);
      console.log(`Response: ${text.substring(0, 200)}`);
      
      if (response.ok) {
        console.log('✅ SUCCESS!');
        return;
      }
    } catch (err) {
      console.error(`Error: ${err.message}`);
    }
    console.log('---');
  }
}

trySqlEndpoints();
