
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function tryExecSql() {
  const sql = `
CREATE TABLE IF NOT EXISTS uploaded_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id VARCHAR(255) NOT NULL,
  patient_name VARCHAR(255) DEFAULT NULL,
  bill_date DATE DEFAULT NULL,
  total_amount DECIMAL(10,2) DEFAULT 0.00,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_data TEXT NOT NULL, -- Base64 encoded file data
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_uploaded_bills_allocation_id ON uploaded_bills(allocation_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_bills_upload_date ON uploaded_bills(upload_date);
  `;

  console.log('Attempting to execute SQL via RPC...');
  try {
    const { data, error } = await supabase.rpc('exec_sql', { sql_query: sql });
    
    if (error) {
      console.error('RPC Error:', error);
      console.log('It seems "exec_sql" RPC is not available or failed.');
    } else {
      console.log('Success! Table created.', data);
    }
  } catch (err) {
    console.error('Unexpected error:', err);
  }
}

tryExecSql();
